version: "0.5"

processes:
  init-postgres:
    command: devbox run init-postgres

  # postgresql:
  #   command: 'pg_ctl start -o "-k $PGHOST"'
  #   is_daemon: true
  #   depends_on:
  #     init-postgres:
  #       condition: process_completed_successfully
  #   shutdown: 
  #     command: pg_ctl stop -m fast
  #   readiness_probe:
  #     period_seconds: 1
  #     exec:
  #       command: pg_isready -U postgres
  #   availability: 
  #     restart: always
  #
  #
  # prepare-dbs:
  #   command: "mix do ecto.create, ecto.migrate"
  #   depends_on:
  #     postgresql:
  #       condition: process_healthy
